# 基础镜像
FROM nginx
# author
MAINTAINER x5

# 挂载目录
VOLUME /home/x5/projects/x5-ui
# 创建目录
RUN mkdir -p /home/x5/projects/x5-ui
# 指定路径
WORKDIR /home/x5/projects/x5-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/x5/projects/x5-ui
